# =========== libcopp/src - fcontext : ${LIBCOPP_FCONTEXT_OS_PLATFORM} - sysv - ${LIBCOPP_FCONTEXT_BIN_FORMAT} - ${LIBCOPP_FCONTEXT_AS_TOOL} ===========
file(MAKE_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}")

find_program(LIBCOPP_FCONTEXT_AS_TOOL_BIN as)
if(NOT LIBCOPP_FCONTEXT_AS_TOOL_BIN)
    EchoWithColor(COLOR RED "-- as not found in path, please add as's directory into path")
    message(FATAL_ERROR "as not found")
endif()

find_program(LIBCOPP_FCONTEXT_AS_TOOL_BINC cpp)
if(NOT LIBCOPP_FCONTEXT_AS_TOOL_BIN)
    EchoWithColor(COLOR RED "-- cpp not found in path, please add cpp's directory into path")
    message(FATAL_ERROR "cpp not found")
endif()

if (WIN32 OR WINCE OR WINDOWS_PHONE OR WINDOWS_STORE OR MINGW OR CYGWIN)
    set(PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_MAKE "${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_MAKE}.asm")
    set(PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_JUMP "${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_JUMP}.asm")
else()
    set(PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_MAKE "${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_MAKE}.S")
    set(PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_JUMP "${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_JUMP}.S")
endif()

if(LIBCOPP_FCONTEXT_AS_ACTION)
    set(LIBCOPP_FCONTEXT_AS_ACTION "--${LIBCOPP_FCONTEXT_AS_ACTION}")
endif()

execute_process (
    COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BINC} -x assembler-with-cpp "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_MAKE}"
    COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BIN} ${LIBCOPP_FCONTEXT_AS_ACTION} -o "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}"
	WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
)

execute_process (
    COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BINC} -x assembler-with-cpp "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_FILE_JUMP}"
    COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BIN} ${LIBCOPP_FCONTEXT_AS_ACTION} -o "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}"
    WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
)

list(APPEND COPP_SRC_LIST "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}")
