# =========== libcopp/src - fcontext : ${LIBCOPP_FCONTEXT_OS_PLATFORM} - sysv - ${LIBCOPP_FCONTEXT_BIN_FORMAT} - ${LIBCOPP_FCONTEXT_AS_T
file(MAKE_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}")
	
if(MSVC)
	list(APPEND COPP_SRC_LIST
		"${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_MAKE}.asm"
        "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_JUMP}.asm"
	)
	set(MASMFound FALSE)
	enable_language(ASM_MASM)
	if(CMAKE_ASM_MASM_COMPILER_WORKS)
		SET(MASMFound TRUE)
	else()
		EchoWithColor(COLOR RED "-- enable masm failed")
		message(FATAL_ERROR "enable ASM_MASM failed")
	endif(CMAKE_ASM_MASM_COMPILER_WORKS)
else()
    set (LIBCOPP_FCONTEXT_AS_TOOL_OPTION "/c /Fo")
    if("${LIBCOPP_FCONTEXT_AS_TOOL}" STREQUAL "64")
        set (LIBCOPP_FCONTEXT_AS_BIN "ml64")
    else()
        set (LIBCOPP_FCONTEXT_AS_BIN "ml")
    endif()

    find_program(LIBCOPP_FCONTEXT_AS_TOOL_BIN ${LIBCOPP_FCONTEXT_AS_BIN})
    if(NOT LIBCOPP_FCONTEXT_AS_TOOL_BIN)
        EchoWithColor(COLOR RED "-- ${LIBCOPP_FCONTEXT_AS_BIN} not found in path, please add as's directory into path")
        message(FATAL_ERROR "${LIBCOPP_FCONTEXT_AS_BIN} not found")
    endif()

	execute_process (
        COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BIN} ${LIBCOPP_FCONTEXT_AS_TOOL_OPTION} "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}"
        "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_MAKE}.asm"
        WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
    )
	
	execute_process (
        COMMAND ${LIBCOPP_FCONTEXT_AS_TOOL_BIN} ${LIBCOPP_FCONTEXT_AS_TOOL_OPTION} "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}"
        "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/${PROJECT_LIBCOPP_FCONTEXT_SRC_NAME_JUMP}.asm"
        WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
    )

	list(APPEND COPP_SRC_LIST "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}")
endif()
