# =========== libcopp/src - fcontext : ${LIBCOPP_FCONTEXT_OS_PLATFORM} - ms - ${LIBCOPP_FCONTEXT_BIN_FORMAT} =========== 
set(PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}")
set(PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}")
file(MAKE_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}")
if(CYGWIN)
	execute_process (
        COMMAND cygpath -w "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}" 
		OUTPUT_VARIABLE PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH
    )
	
	execute_process (
        COMMAND cygpath -w "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}" 
		OUTPUT_VARIABLE PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH
    )
	
	string(STRIP "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH}" PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH)
	string(STRIP "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH}" PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH)
endif()
	
if(MSVC)
	list(APPEND COPP_SRC_LIST "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH}/jump_${LIBCOPP_FCONTEXT_OS_PLATFORM}_${LIBCOPP_FCONTEXT_ABI}_${LIBCOPP_FCONTEXT_BIN_FORMAT}.asm" "${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH}/make_${LIBCOPP_FCONTEXT_OS_PLATFORM}_${LIBCOPP_FCONTEXT_ABI}_${LIBCOPP_FCONTEXT_BIN_FORMAT}.asm")
	set(MASMFound FALSE)
	enable_language(ASM_MASM)
	if(CMAKE_ASM_MASM_COMPILER_WORKS)
		SET(MASMFound TRUE)
	else()
		EchoWithColor(COLOR RED "-- enable masm failed")
		message(FATAL_ERROR "enable ASM_MASM failed")
	endif(CMAKE_ASM_MASM_COMPILER_WORKS)
else()
	if ("${LIBCOPP_FCONTEXT_AS_TOOL}" STREQUAL "armasm")
		set (LIBCOPP_FCONTEXT_AS_TOOL_OPTION "")
	else()
		set (LIBCOPP_FCONTEXT_AS_TOOL_OPTION "/c /Fo")
	endif()
	
	execute_process (
        COMMAND "${LIBCOPP_FCONTEXT_AS_TOOL}" ${LIBCOPP_FCONTEXT_AS_TOOL_OPTION} "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}" 
		"${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH}/make_${LIBCOPP_FCONTEXT_OS_PLATFORM}_${LIBCOPP_FCONTEXT_ABI}_${LIBCOPP_FCONTEXT_BIN_FORMAT}.asm"
        WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
    )
	
	execute_process (
        COMMAND "${LIBCOPP_FCONTEXT_AS_TOOL}" ${LIBCOPP_FCONTEXT_AS_TOOL_OPTION} "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR_WINPATH}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" 
		"${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR_WINPATH}/jump_${LIBCOPP_FCONTEXT_OS_PLATFORM}_${LIBCOPP_FCONTEXT_ABI}_${LIBCOPP_FCONTEXT_BIN_FORMAT}.asm"
        WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
    )
	
	list(APPEND COPP_SRC_LIST "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}")
endif()
