# =========== libcopp/src - fcontext : x86_64 - sysv - macho =========== 
file(MAKE_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}")

execute_process (
	COMMAND "${LIBCOPP_FCONTEXT_AS_TOOL}" -o "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}" 
	"${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/make_x86_64_sysv_macho_gas.S"
	WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
)

execute_process (
	COMMAND "${LIBCOPP_FCONTEXT_AS_TOOL}" -o "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" 
	"${PROJECT_LIBCOPP_FCONTEXT_ASM_DIR}/jump_x86_64_sysv_macho_gas.S"
	WORKING_DIRECTORY "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}"
)

list(APPEND COPP_SRC_LIST "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_JUMP}" "${PROJECT_LIBCOPP_FCONTEXT_BIN_DIR}/${PROJECT_LIBCOPP_FCONTEXT_BIN_NAME_MAKE}")
