# 设置实际的默认编译输出目录
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/lib")

set(PROJECT_TARGET_INSTALL_EXECUTABLE_DIR "bin")
set(PROJECT_TARGET_INSTALL_ARCHIVE_DIR "lib")

if (WIN32)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin")
    set(PROJECT_TARGET_INSTALL_LIBRARY_DIR "bin")
    link_directories (${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
else ()
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/lib")
    set(PROJECT_TARGET_INSTALL_LIBRARY_DIR "lib")
endif ()
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(EXECUTABLE_OUTPUT_PATH "${PROJECT_BINARY_DIR}/bin")

link_directories (${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})